#ifndef ENUM_VIEW_TAG_HPP
#define ENUM_VIEW_TAG_HPP

enum class ViewTag : int {
    NONE = -1,
    TITLE_SCREEN,
    SETTINGS_SCREEN,
    MAP_SELECT_SCREEN,
    LEADERBOARD_SCREEN,
    TIMER_VIEW,
    GAME_OVER_SCREEN,
    SCORE_VIEW
};

#endif

